from typing import Any, Callable, Optional, Union, List

class Node:
    def __init__(self, *args, **kwargs): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...

class Section(Node):
    def __init__(self, id: str = "", align: str = "", padding: Union[int, str] = 0, paddingY: Union[int, str] = 0, maxWidth: Union[int, str] = 0, justify: str = "", bg: str = "", radius: Union[int, str] = 0, **kwargs): ...

class Row(Node):
    def __init__(self, align: str = "", justify: str = "", gap: int = 0, wrap: bool = False, color: str = "", **kwargs): ...

class Column(Node):
    def __init__(self, align: str = "", justify: str = "", gap: int = 0, padding: int = 0, bg: str = "", border: str = "", radius: int = 0, minWidth: int = 0, maxWidth: int = 0, **kwargs): ...

class Card(Node):
    def __init__(self, padding: int = 0, bg: str = "", radius: int = 0, **kwargs): ...

class Form(Node):
    def __init__(self, **kwargs): ...

class Heading(Node):
    def __init__(self, text: str = "", color: str = "", size: str = "", weight: str = "", **kwargs): ...

class Text(Node):
    def __init__(self, text: str = "", color: str = "", size: str = "", weight: str = "", align: str = "", bg: str = "", padding: str = "", radius: int = 0, border: str = "", action: str = "", dataBind: str = "", **kwargs): ...

class GradientText(Node):
    def __init__(self, text: str = "", gradient: List[str] = [], size: str = "", **kwargs): ...

class Button(Node):
    def __init__(self, text: str = "", variant: str = "", glow: str = "", radius: str = "", action: str = "", on_click: str = "", hoverEffect: str = "", clickEffect: str = "", **kwargs): ...

class Input(Node):
    def __init__(self, placeholder: str = "", dataBind: str = "", width: str = "", padding: int = 0, bg: str = "", border: str = "", radius: int = 0, color: str = "", **kwargs): ...

class AnimatedBackground(Node):
    def __init__(self, effect: str = "", primaryColor: str = "", secondaryColor: str = "", **kwargs): ...

class Navbar(Node):
    def __init__(self, padding: int = 0, blur: bool = False, fixed: bool = False, **kwargs): ...

class NavLink(Node):
    def __init__(self, text: str = "", route: str = "", **kwargs): ...

class Marquee(Node):
    def __init__(self, direction: str = "", speed: str = "", **kwargs): ...

class HeroContainer(Node):
    def __init__(self, heroBackground: str = "", entranceChoreography: str = "", **kwargs): ...

class Span(Node):
    def __init__(self, text: str = "", **kwargs): ...

class Keyframes:
    def __init__(self, keyframes: dict): ...
    @classmethod
    def transition(cls, type: str = "", duration: str = "", **kwargs) -> 'Keyframes': ...

class Container(Node):
    def __init__(self, align: str = "", justify: str = "", width: Union[int, str] = 0, padding: Union[int, str] = 0, animation: Optional[Keyframes] = None, duration: str = "", **kwargs): ...

class CustomShader(Node):
    def __init__(self, fragment_code: str, uniforms: dict = {}, **kwargs): ...

class Surface(Node):
    def __init__(self, width: Union[int, str] = 0, height: Union[int, str] = 0, background: str = "", **kwargs): ...

class Router(Node):
    def __init__(self, default_route: str = "/", global_transition: Optional[Keyframes] = None, transitionIn: str = "", transitionOut: str = "", transitionDuration: str = "", **kwargs): ...

class Route(Node):
    def __init__(self, path: str = "", scene: Any = None, component: str = "", transition: Optional[Keyframes] = None, **kwargs): ...

class Preload(Node):
    def __init__(self, **kwargs): ...

class Font(Node):
    def __init__(self, url: str = "", **kwargs): ...

class Image(Node):
    def __init__(self, src: str = "", url: str = "", assetPriority: str = "", **kwargs): ...

class Spacer(Node):
    def __init__(self, height: int = 0, width: int = 0, **kwargs): ...

class Grid(Node):
    def __init__(self, cols: int = 1, gap: int = 0, **kwargs): ...

class Footer(Node):
    def __init__(self, padding: int = 0, align: str = "", **kwargs): ...

# Global functions
def TinUIMutateState(key: str, val: Any): ...
def register_state(key: str, val: Any): ...
