from typing import Any, Callable, Optional, Union, List

class Node:
    def __init__(self, *args, **kwargs): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...

class Section(Node):
    def __init__(self, id: str = "", align: str = "", padding: Union[int, str] = 0, paddingY: Union[int, str] = 0, maxWidth: Union[int, str] = 0, justify: str = "", bg: str = "", radius: Union[int, str] = 0, **kwargs): ...

class Row(Node):
    def __init__(self, align: str = "", justify: str = "", gap: int = 0, wrap: bool = False, color: str = "", **kwargs): ...

class Column(Node):
    def __init__(self, align: str = "", justify: str = "", gap: int = 0, padding: int = 0, bg: str = "", border: str = "", radius: int = 0, minWidth: int = 0, maxWidth: int = 0, **kwargs): ...

class Card(Node):
    def __init__(self, padding: int = 0, bg: str = "", radius: int = 0, **kwargs): ...

class Form(Node):
    def __init__(self, **kwargs): ...

class Heading(Node):
    def __init__(self, text: str = "", color: str = "", size: str = "", weight: str = "", **kwargs): ...

class Text(Node):
    def __init__(self, text: str = "", color: str = "", size: str = "", weight: str = "", align: str = "", bg: str = "", padding: str = "", radius: int = 0, border: str = "", action: str = "", dataBind: str = "", **kwargs): ...

class GradientText(Node):
    def __init__(self, text: str = "", gradient: List[str] = [], size: str = "", **kwargs): ...

class Button(Node):
    def __init__(self, text: str = "", variant: str = "", glow: str = "", radius: str = "", action: str = "", on_click: str = "", hoverEffect: str = "", clickEffect: str = "", **kwargs): ...

class Input(Node):
    def __init__(self, placeholder: str = "", dataBind: str = "", width: str = "", padding: int = 0, bg: str = "", border: str = "", radius: int = 0, color: str = "", **kwargs): ...

class AnimatedBackground(Node):
    def __init__(self, effect: str = "", primaryColor: str = "", secondaryColor: str = "", **kwargs): ...

class Navbar(Node):
    def __init__(self, padding: int = 0, blur: bool = False, fixed: bool = False, **kwargs): ...

class NavLink(Node):
    def __init__(self, text: str = "", route: str = "", **kwargs): ...

class Marquee(Node):
    def __init__(self, direction: str = "", speed: str = "", **kwargs): ...

class HeroContainer(Node):
    def __init__(self, heroBackground: str = "", entranceChoreography: str = "", **kwargs): ...

class Span(Node):
    def __init__(self, text: str = "", **kwargs): ...

class Keyframes:
    def __init__(self, keyframes: dict): ...
    @classmethod
    def transition(cls, type: str = "", duration: str = "", **kwargs) -> 'Keyframes': ...

class Container(Node):
    def __init__(self, align: str = "", justify: str = "", width: Union[int, str] = 0, padding: Union[int, str] = 0, animation: Optional[Keyframes] = None, duration: str = "", **kwargs): ...

class CustomShader(Node):
    def __init__(self, fragment_code: str, uniforms: dict = {}, **kwargs): ...

class Surface(Node):
    def __init__(self, width: Union[int, str] = 0, height: Union[int, str] = 0, background: str = "", **kwargs): ...

class Router(Node):
    def __init__(self, default_route: str = "/", global_transition: Optional[Keyframes] = None, transitionIn: str = "", transitionOut: str = "", transitionDuration: str = "", **kwargs): ...

class Route(Node):
    def __init__(self, path: str = "", scene: Any = None, component: str = "", transition: Optional[Keyframes] = None, **kwargs): ...

class Preload(Node):
    def __init__(self, **kwargs): ...

class Font(Node):
    def __init__(self, url: str = "", **kwargs): ...

class Image(Node):
    def __init__(self, src: str = "", url: str = "", assetPriority: str = "", **kwargs): ...

class Spacer(Node):
    def __init__(self, height: int = 0, width: int = 0, **kwargs): ...

class Grid(Node):
    def __init__(self, cols: int = 1, gap: int = 0, **kwargs): ...

class Footer(Node):
    def __init__(self, padding: int = 0, align: str = "", **kwargs): ...

# Global functions
def TinUIMutateState(key: str, val: Any): ...
def register_state(key: str, val: Any): ...

class App:
    def __init__(self, title: str = "TinPyUI App", width: int = 1000, height: int = 700): ...
    def run(self) -> None: ...

class Window(App): ...

def create_window(title: str = "TinPyUI App", width: int = 1000, height: int = 700) -> App: ...
def run(app: Optional[App] = None) -> None: ...
def export_mobile(target_file: str = "main.tin", output_dir: str = "build/mobile/android", app_name: str = "TinPyUI App", package_name: str = "com.tinpyui.app", build_apk: bool = False) -> str: ...
def export_android(target_file: str = "main.tin", output_dir: str = "build/mobile/android", app_name: str = "TinPyUI App", package_name: str = "com.tinpyui.app", build_apk: bool = False) -> str: ...
def export_ios(target_file: str = "main.tin", output_dir: str = "build/mobile/ios", app_name: str = "TinPyUI App", bundle_id: str = "com.tinpyui.app", build_ipa: bool = False) -> Dict[str, str]: ...

class DataGrid(Node):
    def __init__(self, columns: Optional[List[Union[str, Dict[str, Any]]]] = None, data: Any = None, page_size: int = 10, searchable: bool = True, sortable: bool = True, selectable: bool = False, exportable: bool = True, **kwargs): ...
    def set_search(self, query: str) -> None: ...
    def sort_by(self, col_key: str, ascending: Optional[bool] = None) -> None: ...
    def set_page(self, page_number: int) -> None: ...
    def export_csv(self) -> str: ...
    def export_json(self) -> str: ...

class AIChat(Node):
    def __init__(self, messages: Optional[Union[List[Dict[str, Any]], Signal]] = None, model_name: str = "AI Assistant", avatar: Optional[str] = None, user_avatar: Optional[str] = None, placeholder: str = "Ask anything...", on_send: Optional[Callable[[str], None]] = None, height: str = "600px", **kwargs): ...
    def append_message(self, role: str, content: str, meta: Optional[Dict[str, Any]] = None) -> None: ...
    def start_stream(self, role: str = "assistant", initial_token: str = "") -> None: ...
    def stream_token(self, token: str) -> None: ...
    def end_stream(self) -> None: ...
    def clear(self) -> None: ...

class ColorPicker(Node):
    def __init__(self, value: Union[str, Signal] = "#00f2fe", presets: Optional[List[str]] = None, show_alpha: bool = True, show_presets: bool = True, on_change: Optional[Callable[[str], None]] = None, **kwargs): ...
    def set_color(self, hex_or_rgba: str) -> None: ...
    @property
    def color(self) -> str: ...

class Calendar(Node):
    def __init__(self, year: Optional[int] = None, month: Optional[int] = None, selected_date: Optional[Union[str, Signal]] = None, on_select: Optional[Callable[[str], None]] = None, **kwargs): ...
    def select_date(self, date_str: str) -> None: ...
    def next_month(self) -> None: ...
    def prev_month(self) -> None: ...

class DatePicker(Node):
    def __init__(self, value: Optional[Union[str, Signal]] = None, placeholder: str = "Select date...", date_format: str = "%Y-%m-%d", min_date: Optional[str] = None, max_date: Optional[str] = None, presets: bool = True, on_change: Optional[Callable[[str], None]] = None, **kwargs): ...
    def set_value(self, val: str) -> None: ...

class Chart(Node):
    def __init__(self, chart_type: str = "line", data: Optional[Union[List[Any], Signal]] = None, labels: Optional[List[str]] = None, width: str = "100%", height: str = "300px", colors: Optional[List[str]] = None, title: Optional[str] = None, **kwargs): ...
    def set_data(self, new_data: List[Any], new_labels: Optional[List[str]] = None) -> None: ...
    def render_svg(self) -> str: ...

class LineChart(Chart): ...
class BarChart(Chart): ...
class DonutChart(Chart): ...
class Sparkline(Chart): ...

class TreeNode:
    def __init__(self, id: str, label: str, icon: Optional[str] = None, children: Optional[List[TreeNode]] = None, expanded: bool = False, data: Any = None): ...

class TreeView(Node):
    def __init__(self, nodes: Optional[List[Union[TreeNode, Dict[str, Any]]]] = None, selected_id: Optional[str] = None, on_select: Optional[Callable[[Dict[str, Any]], None]] = None, **kwargs): ...
    def select_node(self, node_id: str) -> None: ...
    def toggle_expand(self, node_id: str) -> None: ...

class RedisDatabase:
    def __init__(self, uri: str = "redis://localhost:6379/0", **kwargs): ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any, ex: Optional[int] = None) -> bool: ...
    def delete(self, *keys: str) -> int: ...
    def signal(self, key: str, default: Any = None) -> Signal: ...
    def pubsub_signal(self, channel: str, default: Any = None) -> Signal: ...
    def publish(self, channel: str, message: Any) -> int: ...
    def subscribe(self, channel: str, callback: Callable[[str, Any], None]) -> None: ...

class DuckDBDatabase:
    def __init__(self, uri: str = "duckdb://:memory:", **kwargs): ...
    def query(self, sql: str, params: Optional[List[Any]] = None) -> List[Dict[str, Any]]: ...
    def live_query(self, sql: str, params: Optional[List[Any]] = None, interval: float = 1.0) -> Signal: ...
    def execute(self, sql: str, params: Optional[List[Any]] = None) -> Any: ...

class Container(Node):
    def __init__(self, **kwargs): ...

class Grid(Node):
    def __init__(self, cols: Union[int, str] = 1, gap: Union[int, str] = 16, **kwargs): ...

class Surface(Node):
    def __init__(self, **kwargs): ...

class Header(Node):
    def __init__(self, **kwargs): ...

class Footer(Node):
    def __init__(self, **kwargs): ...

class Main(Node):
    def __init__(self, **kwargs): ...

class Modal(Node):
    def __init__(self, open: bool = False, **kwargs): ...

class Tooltip(Node):
    def __init__(self, text: str = "", **kwargs): ...

class ShaderLayer(Node):
    def __init__(self, effect: str = "black_hole", speed: Union[float, str] = 1.0, intensity: Union[float, str] = 1.0, **kwargs): ...

class WebGLCanvas(Node):
    def __init__(self, id: str = "shader-canvas", preset: str = "black_hole", fragmentCode: str = "", **kwargs): ...

class ParticleField(Node):
    def __init__(self, count: int = 60, color: str = "neon-purple", speed: float = 1.0, interactive: bool = True, **kwargs): ...

class Icon(Node):
    def __init__(self, name: str = "", size: str = "", color: str = "", **kwargs): ...

class Link(Node):
    def __init__(self, text: Any = "", href: str = "#", target: str = "", onClick: str = "", **kwargs): ...

class ShaderPreset:
    BLACK_HOLE: str
    PILLARS_OF_CREATION: str
    SUPERNOVA_NEBULA: str
    CYBER_MESH: str
    AURORA_FLUX: str
    FLUID_PARTICLES: str
    VOLUMETRIC_FOG: str
    BLOOM: str
    OFF: str
    ALL: List[str]

class GpuPerformanceMode:
    ULTRA_ECO: float
    ECO: float
    BALANCED: float
    NATIVE: float

def get_shader_code(preset: str) -> str: ...
def set_shader_preset(preset: str) -> str: ...
def set_gpu_mode(mode: Union[float, str]) -> str: ...

class Morphism:
    GLASS: str
    NEUMORPHIC: str
    CLAY: str
    HOLO: str
    ALL: List[str]

def get_morphism_style(morphism_name: str) -> str: ...

class RedirectTransition:
    QUANTUM_WARP: str
    SHUTTER: str
    PRISMATIC_BLUR: str
    GATEWAY_TUNNEL: str
    QUANTUM_PORTAL: str
    ALL: List[str]

def redirect_page(destination_name: str, target_url: str, transition_style: str = "Quantum Warp") -> str: ...
def show_toast(message: str, toast_type: str = "cyan") -> str: ...

class ScrollSpeedPreset:
    GLIDE: float
    STANDARD: float
    TURBO: float
    HYPER: float

def set_scroll_speed(multiplier: Union[float, str]) -> str: ...
def toggle_auto_scroll(active: Optional[bool] = None) -> str: ...


